# Generated by Django 4.2.30 on 2026-07-24 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('diseases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('screened', 'Screened'), ('diagnosed', 'Diagnosed'), ('enrolled', 'Enrolled'), ('ineligible', 'Ineligible'), ('died', 'Deceased'), ('ltfu', 'Loss to Follow-Up'), ('withdrawn', 'Withdrawn Consent'), ('transferred', 'Transferred Out'), ('defaulted', 'Defaulted')], default='registered', max_length=20)),
                ('status_date', models.DateField(blank=True, help_text='Date of death, LTFU, or transfer', null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20)),
                ('follow_up_interval_months', models.IntegerField(default=1, help_text='Follow-up interval in months')),
                ('passport_size_photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='sites.site')),
                ('registered_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='sites.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_of_screening', models.DateField(blank=True, null=True)),
                ('is_permanent_resident', models.BooleanField(default=True)),
                ('known_ncd', models.BooleanField(default=False)),
                ('type_of_screening', models.CharField(choices=[('facility', 'Facility'), ('community', 'Community'), ('mobile', 'Mobile Clinic')], default='facility', max_length=20)),
                ('screening_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ordered_tests', models.ManyToManyField(blank=True, related_name='screening_orders', to='diagnostics.diagnostictest')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='patients.patient')),
                ('suspected_diseases', models.ManyToManyField(blank=True, related_name='screenings', to='diseases.disease')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('screened', 'Screened'), ('diagnosed', 'Diagnosed'), ('enrolled', 'Enrolled'), ('ineligible', 'Ineligible'), ('died', 'Deceased'), ('ltfu', 'Loss to Follow-Up'), ('withdrawn', 'Withdrawn Consent'), ('transferred', 'Transferred Out'), ('defaulted', 'Defaulted')], default='registered', max_length=20)),
                ('status_date', models.DateField(blank=True, help_text='Date of death, LTFU, or transfer', null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20)),
                ('follow_up_interval_months', models.IntegerField(default=1, help_text='Follow-up interval in months')),
                ('passport_size_photo', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registered_site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical patient',
                'verbose_name_plural': 'historical patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('cohort', models.CharField(blank=True, choices=[('cardiac', 'Cardiac'), ('scd', 'SCD'), ('dm', 'DM')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Explanation if not eligible', null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('enrollment_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('date_of_consent', models.DateField(blank=True, null=True)),
                ('diagnosis', models.TextField()),
                ('confirmed_cardiac_type', models.CharField(blank=True, choices=[('rhd', 'RHD (Rheumatic Heart Disease)'), ('chd', 'CHD (Congenital Heart Disease)'), ('hf', 'HF (Heart Failure)'), ('arth', 'ARTH (Arrhythmia)')], max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('confirmed_diseases', models.ManyToManyField(blank=True, related_name='diagnoses', to='diseases.disease')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
