# Generated by Django 4.2.30 on 2026-07-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='date_of_consent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('screened', 'Screened'), ('diagnosed', 'Diagnosed'), ('eligible', 'Eligible'), ('enrolled', 'Enrolled'), ('ineligible', 'Ineligible'), ('died', 'Deceased'), ('ltfu', 'Loss to Follow-Up'), ('withdrawn', 'Withdrawn Consent'), ('transferred', 'Transferred Out'), ('defaulted', 'Defaulted')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('screened', 'Screened'), ('diagnosed', 'Diagnosed'), ('eligible', 'Eligible'), ('enrolled', 'Enrolled'), ('ineligible', 'Ineligible'), ('died', 'Deceased'), ('ltfu', 'Loss to Follow-Up'), ('withdrawn', 'Withdrawn Consent'), ('transferred', 'Transferred Out'), ('defaulted', 'Defaulted')], default='registered', max_length=20),
        ),
    ]
