# Generated by Django 4.2.30 on 2026-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='confirmed_cardiac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='confirmed_cardiac_type',
            field=models.CharField(blank=True, choices=[('rhd', 'RHD (Rheumatic Heart Disease)'), ('chd', 'CHD (Congenital Heart Disease)'), ('hf', 'HF (Heart Failure)'), ('arth', 'ARTH (Arrhythmia)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='confirmed_dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='confirmed_scd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_cardiac_ecg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_cardiac_echo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_cardiac_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_cardiac_xray',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_dm_c_peptide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_dm_creatinine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_dm_fbg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_dm_hba1c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_dm_rbg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_dm_urea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_scd_echo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_scd_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_scd_radiology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='order_scd_screening',
            field=models.BooleanField(default=False),
        ),
    ]
