# Generated by Django 4.2.30 on 2026-07-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_seed_default_diseases'),
        ('patients', '0002_consultation_confirmed_cardiac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='confirmed_cardiac',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='confirmed_dm',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='confirmed_scd',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='suspect_cardiac',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='suspect_dm',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='suspect_scd',
        ),
        migrations.AddField(
            model_name='consultation',
            name='confirmed_diseases',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='diseases.disease'),
        ),
        migrations.AddField(
            model_name='screening',
            name='suspected_diseases',
            field=models.ManyToManyField(blank=True, related_name='screenings', to='diseases.disease'),
        ),
    ]
