# Generated by Django 4.2.30 on 2026-07-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_enrollment_consent_given_enrollment_date_of_consent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='consent_given',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='date_of_consent',
        ),
    ]
