# Generated by Django 4.2.30 on 2026-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_seed_default_tests'),
        ('patients', '0003_remove_consultation_confirmed_cardiac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dminvestigation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dminvestigation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='dminvestigation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='scdinvestigation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scdinvestigation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='scdinvestigation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_cardiac_ecg',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_cardiac_echo',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_cardiac_lab',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_cardiac_xray',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_dm_c_peptide',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_dm_creatinine',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_dm_fbg',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_dm_hba1c',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_dm_rbg',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_dm_urea',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_scd_echo',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_scd_lab',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_scd_radiology',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='order_scd_screening',
        ),
        migrations.AddField(
            model_name='screening',
            name='ordered_tests',
            field=models.ManyToManyField(blank=True, related_name='screening_orders', to='laboratory.labtest'),
        ),
        migrations.DeleteModel(
            name='CardiacInvestigation',
        ),
        migrations.DeleteModel(
            name='DMInvestigation',
        ),
        migrations.DeleteModel(
            name='SCDInvestigation',
        ),
    ]
