# Generated by Django 4.2.30 on 2026-07-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_config', '0001_initial'),
        ('patients', '0003_remove_diagnosis_consent_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='assigned_forms',
            field=models.ManyToManyField(blank=True, related_name='screenings', to='study_config.clinicalform'),
        ),
    ]
