# Generated by Django 4.2.30 on 2026-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_dminvestigation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='remarks',
            field=models.TextField(blank=True, help_text='Explanation if not eligible', null=True),
        ),
    ]
