# Generated by Django 4.2.30 on 2026-07-20 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_seed_default_diseases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0005_enrollment_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultation',
            new_name='Diagnosis',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='confirmed_diseases',
            field=models.ManyToManyField(blank=True, related_name='diagnoses', to='diseases.disease'),
        ),
    ]
