# Generated by Django 4.2.30 on 2026-07-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_id_number_patient_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='follow_up_interval_months',
            field=models.IntegerField(default=1, help_text='Follow-up interval in months'),
        ),
        migrations.AddField(
            model_name='patient',
            name='follow_up_interval_months',
            field=models.IntegerField(default=1, help_text='Follow-up interval in months'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('screened', 'Screened'), ('diagnosed', 'Diagnosed'), ('enrolled', 'Enrolled'), ('ineligible', 'Ineligible'), ('died', 'Deceased'), ('ltfu', 'Loss to Follow-Up'), ('withdrawn', 'Withdrawn Consent'), ('transferred', 'Transferred Out'), ('defaulted', 'Defaulted')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('screened', 'Screened'), ('diagnosed', 'Diagnosed'), ('enrolled', 'Enrolled'), ('ineligible', 'Ineligible'), ('died', 'Deceased'), ('ltfu', 'Loss to Follow-Up'), ('withdrawn', 'Withdrawn Consent'), ('transferred', 'Transferred Out'), ('defaulted', 'Defaulted')], default='registered', max_length=20),
        ),
    ]
