# Generated by Django 4.2.30 on 2026-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_historicalpatient_follow_up_interval_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='status_date',
            field=models.DateField(blank=True, help_text='Date of death, LTFU, or transfer', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status_date',
            field=models.DateField(blank=True, help_text='Date of death, LTFU, or transfer', null=True),
        ),
    ]
