# Generated by Django 4.2.30 on 2026-07-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_historicalpatient_status_date_patient_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='passport_size_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_size_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
