# Generated by Django 4.2.30 on 2026-07-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('patients', '0010_historicalpatient_passport_size_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='current_site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='sites.site'),
        ),
    ]
