# Generated by Django 4.2.30 on 2026-07-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_historicalpatient_registered_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
