# Generated by Django 4.2.30 on 2026-07-23 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_historicalpatient_gender_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpatient',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='gender',
            new_name='sex',
        ),
    ]
