# Generated by Django 4.2.30 on 2026-07-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_rename_gender_historicalpatient_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
