# Generated by Django 4.2.30 on 2026-07-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_enrollment_enrollment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='date_of_consent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='date_of_screening',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='is_permanent_resident',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='known_ncd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='type_of_screening',
            field=models.CharField(choices=[('facility', 'Facility'), ('community', 'Community'), ('mobile', 'Mobile Clinic')], default='facility', max_length=20),
        ),
    ]
