# Generated by Django 4.2.30 on 2026-07-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('accounts', '0002_customuser_date_of_birth_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='users', to='sites.site'),
        ),
    ]
