# Generated by Django 4.2.30 on 2026-07-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_treatment_socioeconomic_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='alcohol_use',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='family_history_ncd',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='physical_inactivity',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='smoking_status',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='unhealthy_diet',
        ),
        migrations.AddField(
            model_name='risk',
            name='alcohol',
            field=models.CharField(choices=[('never', 'Never'), ('current', 'Current'), ('former', 'Former')], default='never', max_length=20),
        ),
        migrations.AddField(
            model_name='risk',
            name='employment_status',
            field=models.CharField(choices=[('student', 'Student'), ('employed', 'Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='risk',
            name='hiv_status',
            field=models.CharField(choices=[('r', 'R (Reactive)'), ('nr', 'NR (Non-Reactive)'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='risk',
            name='ncd_limiting_school',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='risk',
            name='tb_screening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='tb_status',
            field=models.CharField(choices=[('positive', 'Positive: Smear / Xpert / Other'), ('negative', 'Negative: Smear / Xpert / Other'), ('eptb', 'EPTB'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='risk',
            name='tobacco',
            field=models.CharField(choices=[('never', 'Never'), ('current', 'Current'), ('former', 'Former')], default='never', max_length=20),
        ),
    ]
