# Generated by Django 4.2.30 on 2026-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_remove_risk_alcohol_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalization',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='hospitalization',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='hospitalization',
            name='discharge_summary',
        ),
        migrations.RemoveField(
            model_name='hospitalization',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='hospitalization',
            name='reason_for_admission',
        ),
        migrations.RemoveField(
            model_name='hospitalization',
            name='ward',
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='for_ncd',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unset', 'Unset')], default='unset', max_length=5),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='hydroxyurea_dose',
            field=models.IntegerField(blank=True, default=0, help_text='(N/A = 98), (Missing = 99)', null=True),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='hydroxyurea_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='num_hospitalizations_12m',
            field=models.IntegerField(default=0, help_text='(N/A = 98), (Missing = 99)'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='num_hospitalizations_ncd_12m',
            field=models.IntegerField(default=0, help_text='(N/A = 98), (Missing = 99)'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='on_chronic_opioid_therapy',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='on_hydroxyurea',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='pneumococcal_vaccination_up_to_date',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='recent_hospitalizations',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='school_days_missed_last_month',
            field=models.IntegerField(default=0, help_text='(N/A = 98), (Missing = 99)'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='taking_folic_acid',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='taking_insecticide_net',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='taking_malaria_prophylaxis',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='taking_penicillin_prophylaxis',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='transfusions_past_month',
            field=models.IntegerField(default=0, help_text='(N/A = 98), (Missing = 99)'),
        ),
    ]
