# Generated by Django 4.2.30 on 2026-07-21 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounters', '0003_alter_encounter_encounter_type_and_more'),
        ('clinical', '0007_symptom_history_complications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHomeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('appropriate_grade_for_age', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('ncd_limiting_school', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('school_days_missed', models.IntegerField(blank=True, help_text='Days of missed school in past month', null=True)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('referred_from', models.CharField(choices=[('inpatient', 'Inpatient / hospital stay'), ('primary', 'Primary care clinic'), ('outpatient', 'Other outpatient clinic'), ('maternal', 'Maternal health'), ('community', 'Community'), ('self', 'Self'), ('other', 'Other')], default='other', max_length=20)),
                ('agrees_to_home_visits', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('chw_name_available', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('chw_name', models.TextField(blank=True, help_text='CHW Name Details', null=True)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_home_assessment', to='encounters.encounter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School & Home Assessment',
                'verbose_name_plural': 'School & Home Assessments',
            },
        ),
    ]
