# Generated by Django 4.2.30 on 2026-07-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_encounter_encounter_type_and_more'),
        ('clinical', '0008_schoolhomeassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='encounter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_history', to='encounters.encounter'),
        ),
    ]
