# Generated by Django 4.2.30 on 2026-07-23 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_enrollment_enrollment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0010_prescription_historicalprescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickleCellBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('main_diagnosis', models.CharField(blank=True, choices=[('scd', 'Sickle Cell Disease'), ('other', 'Other Hemoglobinopathy')], max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scd_baseline', to='patients.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiabetesBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('main_diagnosis', models.CharField(blank=True, choices=[('type1', 'Type 1 DM'), ('type2', 'Type 2 DM'), ('gestational', 'Gestational DM'), ('unspecified', 'DM not yet specified'), ('other', 'Other')], max_length=20, null=True)),
                ('presentation', models.CharField(blank=True, choices=[('dka_coma', 'DKA with coma'), ('dka_no_coma', 'DKA without coma'), ('ketosis', 'Ketosis'), ('hyperglycemia', 'Hyperglycemia'), ('screening', 'By Screening'), ('none', 'None')], max_length=20, null=True)),
                ('hypertension', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], max_length=10, null=True)),
                ('hypertension_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dm_baseline', to='patients.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
