# Generated by Django 4.2.30 on 2026-07-23 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_enrollment_enrollment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0011_sicklecellbaseline_diabetesbaseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardiacBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('hypertensive_heart_disease', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('coronary_artery_disease', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('severe_uncontrolled_hypertension', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('cardiomyopathy', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('cardiomyopathy_type', models.CharField(blank=True, choices=[('ischemic', 'Ischemic'), ('alcohol', 'Alcohol-related'), ('peripartum', 'Peripartum'), ('arrhythmia', 'Arrhythmia-related'), ('hiv', 'HIV-related'), ('chemotherapy', 'Chemotherapy-related'), ('viral', 'Viral/idiopathic'), ('other', 'Other')], max_length=20, null=True)),
                ('cardiomyopathy_other', models.TextField(blank=True, null=True)),
                ('rheumatic_heart_disease', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('rhd_type', models.CharField(blank=True, choices=[('ms', 'Pure mitral stenosis'), ('mr', 'Pure mitral regurgitation'), ('mixed_mitral', 'Mixed mitral valve disease (MS + MR)'), ('avd', 'Isolated aortic valve disease (AVD)'), ('mmavd', 'Mixed mitral and aortic valve disease (MMAVD)'), ('other', 'Other')], max_length=20, null=True)),
                ('congenital_heart_disease', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('chd_type', models.CharField(blank=True, choices=[('asd', 'ASD'), ('vsd', 'VSD'), ('pda', 'PDA'), ('coarctation', 'Coarctation of aorta'), ('tetralogy', 'Tetralogy of Fallot'), ('other', 'Other')], max_length=20, null=True)),
                ('right_heart_failure', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('right_heart_failure_type', models.CharField(blank=True, choices=[('cld', 'Chronic Lung Disease'), ('other', 'Other')], max_length=20, null=True)),
                ('pericardial_disease', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('pericardial_disease_type', models.CharField(blank=True, choices=[('tb', 'Tuberculosis'), ('hiv', 'HIV'), ('malignancy', 'Malignancy'), ('other', 'Other')], max_length=20, null=True)),
                ('stroke', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('stroke_type', models.CharField(blank=True, choices=[('ischemic', 'Ischemic'), ('hemorrhagic', 'Hemorrhagic'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('arrhythmia', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('arrhythmia_type', models.CharField(blank=True, choices=[('af', 'Atrial fibrillation'), ('other', 'Other')], max_length=20, null=True)),
                ('thromboembolic', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('thromboembolic_type', models.CharField(blank=True, choices=[('pe', 'Pulmonary embolism'), ('dvt', 'DVT'), ('other', 'Other')], max_length=20, null=True)),
                ('any_other_diagnosis', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('other_diagnosis_specify', models.TextField(blank=True, null=True)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardiac_baseline', to='patients.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
