# Generated by Django 4.2.30 on 2026-07-20 10:15

from django.db import migrations


def seed_diseases(apps, schema_editor):
    Disease = apps.get_model('diseases', 'Disease')
    Disease.objects.update_or_create(
        code='SCD',
        defaults={
            'name': 'Sickle Cell Disease',
            'description': 'Sickle Cell Disease (SCD) PEN-Plus cohort program.',
            'is_active': True
        }
    )
    Disease.objects.update_or_create(
        code='DM',
        defaults={
            'name': 'Diabetes Mellitus',
            'description': 'Type 1 and Type 2 Diabetes Mellitus PEN-Plus cohort program.',
            'is_active': True
        }
    )
    Disease.objects.update_or_create(
        code='CARDIAC',
        defaults={
            'name': 'Cardiac Disease',
            'description': 'Rheumatic Heart Disease and other cardiovascular conditions.',
            'is_active': True
        }
    )

def remove_seeded_diseases(apps, schema_editor):
    Disease = apps.get_model('diseases', 'Disease')
    Disease.objects.filter(code__in=['SCD', 'DM', 'CARDIAC']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_diseases, remove_seeded_diseases),
    ]
