# Generated by Django 4.2.30 on 2026-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='disease',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
