# Generated by Django 4.2.30 on 2026-07-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_nature',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_number',
            field=models.IntegerField(blank=True, help_text='0 for Baseline, 1 for Visit 1, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('arrived', 'Arrived / Checked-In'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('not_applicable', 'Not Applicable'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
