# Generated by Django 4.2.30 on 2026-07-24 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMedication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Brand or common name', max_length=150)),
                ('generic_name', models.CharField(blank=True, help_text='Active ingredient(s)', max_length=200, null=True)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup/Suspension'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500, 10, etc.', max_length=100, null=True)),
                ('strength_unit', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('g', 'g'), ('mcg', 'mcg'), ('IU', 'IU'), ('%', '%'), ('pcs', 'pcs'), ('other', 'Other')], default='mg', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current inventory stock level')),
                ('reorder_level', models.PositiveIntegerField(default=20, help_text='Alert when stock falls below this level')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Optional clinical notes or side effects', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical medication',
                'verbose_name_plural': 'historical medications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Brand or common name', max_length=150)),
                ('generic_name', models.CharField(blank=True, help_text='Active ingredient(s)', max_length=200, null=True)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup/Suspension'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500, 10, etc.', max_length=100, null=True)),
                ('strength_unit', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('g', 'g'), ('mcg', 'mcg'), ('IU', 'IU'), ('%', '%'), ('pcs', 'pcs'), ('other', 'Other')], default='mg', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current inventory stock level')),
                ('reorder_level', models.PositiveIntegerField(default=20, help_text='Alert when stock falls below this level')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Optional clinical notes or side effects', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'strength', 'strength_unit', 'form')},
            },
        ),
    ]
