# Generated by Django 4.2.30 on 2026-07-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedication',
            name='reorder_level',
            field=models.PositiveIntegerField(default=20, help_text='Alert when stock falls below this level'),
        ),
        migrations.AddField(
            model_name='medication',
            name='reorder_level',
            field=models.PositiveIntegerField(default=20, help_text='Alert when stock falls below this level'),
        ),
    ]
