# Generated by Django 4.2.30 on 2026-07-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_historicalmedication_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedication',
            name='strength_unit',
            field=models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('g', 'g'), ('mcg', 'mcg'), ('IU', 'IU'), ('%', '%'), ('pcs', 'pcs'), ('other', 'Other')], default='mg', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='strength_unit',
            field=models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('g', 'g'), ('mcg', 'mcg'), ('IU', 'IU'), ('%', '%'), ('pcs', 'pcs'), ('other', 'Other')], default='mg', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmedication',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500, 10, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500, 10, etc.', max_length=100, null=True),
        ),
    ]
