# Generated by Django 4.2.30 on 2026-07-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_historicalmedication_strength_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedication',
            name='name',
            field=models.CharField(help_text='Brand or common name', max_length=150),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(help_text='Brand or common name', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('name', 'strength', 'strength_unit', 'form')},
        ),
    ]
