# Generated by Django 4.2.30 on 2026-07-20 10:26

from django.db import migrations


def seed_tests(apps, schema_editor):
    Disease = apps.get_model('diseases', 'Disease')
    LabTest = apps.get_model('laboratory', 'LabTest')

    scd_disease = Disease.objects.get(code='SCD')
    dm_disease = Disease.objects.get(code='DM')
    cardiac_disease = Disease.objects.get(code='CARDIAC')

    # SCD Tests
    scd_tests = [
        ('Lab (Electrophoresis)', 'scd_lab', 'lab'),
        ('SCD Screening', 'scd_screening', 'lab'),
        ('SCD ECHO', 'scd_echo', 'cardiology'),
        ('Bone X-Ray', 'scd_xray', 'radiology'),
    ]
    for name, code, category in scd_tests:
        lt, _ = LabTest.objects.update_or_create(code=code, defaults={'name': name, 'category': category})
        lt.diseases.add(scd_disease)

    # DM Tests
    dm_tests = [
        ('HbA1c', 'hba1c', 'lab'),
        ('C-Peptide', 'c_peptide', 'lab'),
        ('Creatinine', 'creatinine', 'lab'),
        ('Urea', 'urea', 'lab'),
        ('Random Blood Glucose (RBG)', 'rbg', 'lab'),
        ('Fasting Blood Glucose (FBG)', 'fbg', 'lab'),
    ]
    for name, code, category in dm_tests:
        lt, _ = LabTest.objects.update_or_create(code=code, defaults={'name': name, 'category': category})
        lt.diseases.add(dm_disease)

    # Cardiac Tests
    cardiac_tests = [
        ('Cardiac Lab Panel', 'cardiac_lab', 'lab'),
        ('Cardiac ECHO', 'cardiac_echo', 'cardiology'),
        ('ECG', 'ecg', 'cardiology'),
        ('Chest X-Ray', 'cardiac_xray', 'radiology'),
    ]
    for name, code, category in cardiac_tests:
        lt, _ = LabTest.objects.update_or_create(code=code, defaults={'name': name, 'category': category})
        lt.diseases.add(cardiac_disease)

def remove_seeded_tests(apps, schema_editor):
    LabTest = apps.get_model('laboratory', 'LabTest')
    LabTest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('diseases', '0002_seed_default_diseases'),
    ]

    operations = [
        migrations.RunPython(seed_tests, remove_seeded_tests),
    ]
