# Generated by Django 4.2.30 on 2026-07-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_seed_default_tests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patienttestresult',
            unique_together=set(),
        ),
    ]
