# Generated by Django 4.2.30 on 2026-07-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('laboratory', '0003_alter_patienttestresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttestresult',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='patienttestresult',
            name='performed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
