# Generated by Django 4.2.30 on 2026-07-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_patienttestresult_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='is_panel',
            field=models.BooleanField(default=False, help_text='If True, this is a group of tests (e.g. BMP).'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='parent_panel',
            field=models.ForeignKey(blank=True, help_text='If this test is part of a panel, link it here.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tests', to='laboratory.labtest'),
        ),
    ]
