# Generated by Django 4.2.30 on 2026-07-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_labtest_is_panel_labtest_parent_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lab_category',
            field=models.CharField(blank=True, choices=[('Haematology', 'Haematology'), ('Serology', 'Serology'), ('Parasitology', 'Parasitology'), ('Clinical Chemistry', 'Clinical Chemistry'), ('Microbiology', 'Microbiology'), ('Bacteriology', 'Bacteriology')], help_text='Specific laboratory category', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='lab_sub_category',
            field=models.CharField(blank=True, choices=[('Haematology', 'Haematology'), ('Serology', 'Serology'), ('Parasitology', 'Parasitology'), ('Renal Function Test', 'Renal Function Test'), ('Liver Function Test', 'Liver Function Test'), ('Thyroid Function Test', 'Thyroid Function Test'), ('Metabolic/Electrolytes', 'Metabolic/Electrolytes'), ('Lipid Panel/Cardiac', 'Lipid Panel/Cardiac'), ('Diabetic', 'Diabetic'), ('Tumor Marker', 'Tumor Marker'), ('Fertility', 'Fertility'), ('Microbiology', 'Microbiology'), ('Bacteriology', 'Bacteriology')], help_text='Specific laboratory sub-category', max_length=50, null=True),
        ),
    ]
