# Generated by Django 4.2.30 on 2026-07-23 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0006_labtest_lab_category_labtest_lab_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. Haematology, Clinical Chemistry', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lab Categories',
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of the test', max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_range',
            field=models.CharField(blank=True, help_text="e.g. '12.5 - 18.0', '0-0', 'N/A'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='units',
            field=models.CharField(blank=True, help_text="e.g. 'g/dl', 'Reactive'", max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LabSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. Renal Function Test', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='laboratory.labcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lab Sub Categories',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='labtest',
            name='lab_category',
            field=models.ForeignKey(blank=True, help_text='Specific laboratory category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.labcategory'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='lab_sub_category',
            field=models.ForeignKey(blank=True, help_text='Specific laboratory sub-category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.labsubcategory'),
        ),
    ]
