# Generated by Django 4.2.30 on 2026-07-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_labcategory_labtest_cost_labtest_reference_range_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabCategory',
            new_name='LaboratoryCategory',
        ),
        migrations.RenameModel(
            old_name='LabSubCategory',
            new_name='LaboratoryType',
        ),
        migrations.RenameModel(
            old_name='LabTest',
            new_name='LaboratoryTest',
        ),
        migrations.RenameField(
            model_name='laboratorytest',
            old_name='lab_category',
            new_name='laboratory_category',
        ),
        migrations.RenameField(
            model_name='laboratorytest',
            old_name='lab_sub_category',
            new_name='laboratory_type',
        ),
        migrations.AlterModelOptions(
            name='laboratorycategory',
            options={'verbose_name_plural': 'Laboratory Categories'},
        ),
        migrations.AlterModelOptions(
            name='laboratorytype',
            options={'verbose_name_plural': 'Laboratory Types'},
        ),
    ]
