# Generated by Django 4.2.30 on 2026-07-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_seed_default_diseases'),
        ('laboratory', '0008_rename_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorytest',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='laboratory_tests', to='diseases.disease'),
        ),
        migrations.AlterField(
            model_name='laboratorytest',
            name='laboratory_type',
            field=models.ForeignKey(blank=True, help_text='Specific laboratory type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.laboratorytype'),
        ),
        migrations.AlterField(
            model_name='laboratorytype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='laboratory.laboratorycategory'),
        ),
    ]
