# Generated by Django 4.2.30 on 2026-07-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_alter_laboratorytest_diseases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorytest',
            name='category',
        ),
    ]
