# Generated by Django 4.2.30 on 2026-07-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_remove_laboratorytest_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorytest',
            name='diseases',
        ),
    ]
