# Generated by Django 4.2.30 on 2026-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_remove_laboratorytest_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorytest',
            name='range_max',
            field=models.CharField(blank=True, help_text="e.g. '18.0', '0', 'N/A'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='range_min',
            field=models.CharField(blank=True, help_text="e.g. '12.5', '0', 'Negative'", max_length=50, null=True),
        ),
    ]
