# Generated by Django 4.2.30 on 2026-07-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_laboratorytest_range_max_laboratorytest_range_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorytest',
            name='reference_range',
        ),
    ]
