# Generated by Django 4.2.30 on 2026-07-23 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0013_remove_laboratorytest_reference_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttestresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patienttestresult',
            name='flag',
            field=models.CharField(blank=True, help_text='e.g. High, Low, Critical', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patienttestresult',
            name='notes',
            field=models.TextField(blank=True, help_text='Lab tech comments', null=True),
        ),
    ]
