# Generated by Django 4.2.30 on 2026-07-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('screening', 'Screening'), ('initial', 'Baseline'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Checkup')], default='routine', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalencounter',
            name='encounter_type',
            field=models.CharField(choices=[('screening', 'Screening'), ('initial', 'Baseline'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Checkup')], default='routine', max_length=20),
        ),
    ]
