# Generated by Django 4.2.30 on 2026-07-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='visit_nature',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalencounter',
            name='visit_nature',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled')], max_length=20, null=True),
        ),
    ]
