# Generated by Django 4.2.30 on 2026-07-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_encounter_visit_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('initial', 'Baseline'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Checkup')], default='routine', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalencounter',
            name='encounter_type',
            field=models.CharField(choices=[('initial', 'Baseline'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Checkup')], default='routine', max_length=20),
        ),
    ]
