# Generated by Django 4.2.30 on 2026-07-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_code',
            field=models.CharField(blank=True, help_text='e.g. KND for Kondoa', max_length=10, null=True, unique=True),
        ),
    ]
