# Generated by Django 4.2.30 on 2026-07-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_site_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_code',
            field=models.CharField(help_text='e.g. KND for Kondoa', max_length=10, unique=True),
        ),
    ]
