# Generated by Django 4.2.30 on 2026-07-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_encounter_encounter_type_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='encounters.encounter'),
        ),
    ]
