# Generated by Django 4.2.30 on 2026-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followuprule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='followuprule',
            name='encounter_type',
            field=models.CharField(choices=[('initial', 'Initial Screening'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Checkup')], default='followup', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='followuprule',
            unique_together={('cohort', 'encounter_type', 'visit_nature')},
        ),
    ]
