# Generated by Django 4.2.30 on 2026-07-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_config', '0002_alter_followuprule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprule',
            name='encounter_type',
            field=models.CharField(choices=[('initial', 'Baseline'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Checkup')], default='followup', max_length=20),
        ),
    ]
