# Generated by Django 4.2.30 on 2026-07-24 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Categories',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. X-ray, Haematology', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_groups', to='departments.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('test_name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(help_text='Unique slug e.g. hba1c, ecg, echo', max_length=50, unique=True)),
                ('range_min', models.CharField(blank=True, help_text="e.g. '12.5', '0', 'Negative'", max_length=50, null=True)),
                ('range_max', models.CharField(blank=True, help_text="e.g. '18.0', '0', 'N/A'", max_length=50, null=True)),
                ('units', models.CharField(blank=True, help_text="e.g. 'g/dl', 'Reactive'", max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of the test', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department this test belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_tests', to='departments.department')),
                ('diagnostic_category', models.ForeignKey(blank=True, help_text='Specific diagnostic category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='diagnostics.diagnosticcategory')),
                ('diagnostic_group', models.ForeignKey(blank=True, help_text='Specific diagnostic group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='diagnostics.diagnosticgroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='diagnosticcategory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='diagnostics.diagnosticgroup'),
        ),
        migrations.AddField(
            model_name='diagnosticcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticcategory',
            unique_together={('group', 'name')},
        ),
    ]
