# Generated by Django 4.2.30 on 2026-07-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_dispensation_order_dispensation_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensation',
            name='batch',
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='quantity_dispensed',
            field=models.PositiveIntegerField(help_text='Total number of pills, bottles, etc. dispensed'),
        ),
        migrations.CreateModel(
            name='DispensationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensation_records', to='pharmacy.inventorybatch')),
                ('dispensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensation_batches', to='pharmacy.dispensation')),
            ],
        ),
    ]
